// var with 1 => checkbox having child checkbox (main parent, no-event checkbox)
// var with 2 => checkbox having child radio (sub parent)

const defaultValues = {
  // // front non-structural
  bmNoevent1: false,
  bmRepaired2: false,
  bmRepaired2Value: '',
  bmReplaced2: false,
  bmReplaced2Value: '',
  bmModified2: false,
  bmModified2Value: '',
  bmExistingDamage2: false,
  bmExistingDamage2Value: '',
  bsNoevent1: false,
  bsRepaired2: false,
  bsRepaired2Value: '',
  bsReplaced2: false,
  bsReplaced2Value: '',
  bsModified2: false,
  bsModified2Value: '',
  bsExistingDamage2: false,
  bsExistingDamage2Value: '',
  // hNoevent1: false,
  // hRepaired2: false,
  // hRepaired2Value: '',
  // hReplaced2: false,
  // hReplaced2Value: '',
  // hModified2: false,
  // hModified2Value: '',
  // hExistingDamage2: false,
  // hExistingDamage2Value: '',
  // drNoevent1: false,
  // drRepaired2: false,
  // drRepaired2Value: '',
  // drReplaced2: false,
  // drReplaced2Value: '',
  // drModified2: false,
  // drModified2Value: '',
  // drExistingDamage2: false,
  // drExistingDamage2Value: '',
  // dlNoevent1: false,
  // dlRepaired2: false,
  // dlRepaired2Value: '',
  // dlReplaced2: false,
  // dlReplaced2Value: '',
  // dlModified2: false,
  // dlModified2Value: '',
  // dlExistingDamage2: false,
  // dlExistingDamage2Value: '',
  // frNoevent1: false,
  // frRepaired2: false,
  // frRepaired2Value: '',
  // frReplaced2: false,
  // frReplaced2Value: '',
  // frModified2: false,
  // frModified2Value: '',
  // frExistingDamage2: false,
  // frExistingDamage2Value: '',
  // flNoevent1: false,
  // flRepaired2: false,
  // flRepaired2Value: '',
  // flReplaced2: false,
  // flReplaced2Value: '',
  // flModified2: false,
  // flModified2Value: '',
  // flExistingDamage2: false,
  // flExistingDamage2Value: '',
  // wrNoevent1: false,
  // wrExistingDamage2: false,
  // wrExistingDamage2Value: '',
  // wlNoevent1: false,
  // wlExistingDamage2: false,
  // wlExistingDamage2Value: '',
  // smrNoevent1: false,
  // smrGlassCracked2: false,
  // smrGlassCracked2Value: '',
  // smrOuterCasingDamage2: false,
  // smrOuterCasingDamage2Value: '',
  smlNoevent1: false,
  smlGlassCracked2: false,
  smlGlassCracked2Value: '',
  smlOuterCasingDamage2: false,
  smlOuterCasingDamage2Value: '',

  // // front structural
  // frrNoevent1: false,
  // frrRepaired2: false,
  // frrRepaired2Value: '',
  // frrReplaced2: false,
  // frrReplaced2Value: '',
  // frrModified2: false,
  // frrModified2Value: '',
  // frrExistingDamage2: false,
  // frrExistingDamage2Value: '',
  // frlNoevent1: false,
  // frlRepaired2: false,
  // frlRepaired2Value: '',
  // frlReplaced2: false,
  // frlReplaced2Value: '',
  // frlModified2: false,
  // frlModified2Value: '',
  // frlExistingDamage2: false,
  // frlExistingDamage2Value: '',
  // mdNoevent1: false,
  // mdExistingDamage: false,
  // aarNoevent1: false,
  // aarRepaired2: false,
  // aarRepaired2Value: '',
  // aarReplaced2: false,
  // aarReplaced2Value: '',
  // aarModified2: false,
  // aarModified2Value: '',
  // aarExistingDamage2: false,
  // aarExistingDamage2Value: '',
  // aalNoevent1: false,
  // aalRepaired2: false,
  // aalRepaired2Value: '',
  // aalReplaced2: false,
  // aalReplaced2Value: '',
  // aalModified2: false,
  // aalModified2Value: '',
  // aalExistingDamage2: false,
  // aalExistingDamage2Value: '',
  // staNoevent1: false,
  // staRepaired2: false,
  // staRepaired2Value: '',
  // staReplaced2: false,
  // staReplaced2Value: '',
  // staModified2: false,
  // staModified2Value: '',
  // staExistingDamage2: false,
  // staExistingDamage2Value: '',
  // cpNoevent1: false,
  // cpRepaired2: false,
  // cpRepaired2Value: '',
  // cpReplaced2: false,
  // cpReplaced2Value: '',
  // cpModified2: false,
  // cpModified2Value: '',
  // cpExistingDamage2: false,
  // cpExistingDamage2Value: '',
  // cmrNoevent1: false,
  // cmrRepaired2: false,
  // cmrRepaired2Value: '',
  // cmrReplaced2: false,
  // cmrReplaced2Value: '',
  // cmrModified2: false,
  // cmrModified2Value: '',
  // cmrExistingDamage2: false,
  // cmrExistingDamage2Value: '',
  // cmrBoltOn2: false,
  // cmlNoevent1: false,
  // cmlRepaired2: false,
  // cmlRepaired2Value: '',
  // cmlReplaced2: false,
  // cmlReplaced2Value: '',
  // cmlModified2: false,
  // cmlModified2Value: '',
  // cmlExistingDamage2: false,
  // cmlExistingDamage2Value: '',
  // cmlBoltOn2: false,
  // sparNoevent1: false,
  // sparRepaired2: false,
  // sparRepaired2Value: '',
  // sparReplaced2: false,
  // sparReplaced2Value: '',
  // sparModified2: false,
  // sparModified2Value: '',
  // sparExistingDamage2: false,
  // sparExistingDamage2Value: '',
  // spalNoevent1: false,
  // spalRepaired2: false,
  // spalRepaired2Value: '',
  // spalReplaced2: false,
  // spalReplaced2Value: '',
  // spalModified2: false,
  // spalModified2Value: '',
  // spalExistingDamage2: false,
  // spalExistingDamage2Value: '',
  // spbrNoevent1: false,
  // spbrRepaired2: false,
  // spbrRepaired2Value: '',
  // spbrReplaced2: false,
  // spbrReplaced2Value: '',
  // spbrModified2: false,
  // spbrModified2Value: '',
  // spbrExistingDamage2: false,
  // spbrExistingDamage2Value: '',
  // spblNoevent1: false,
  // spblRepaired2: false,
  // spblRepaired2Value: '',
  // spblReplaced2: false,
  // spblReplaced2Value: '',
  // spblModified2: false,
  // spblModified2Value: '',
  // spblExistingDamage2: false,
  // spblExistingDamage2Value: '',
  // spcrNoevent1: false,
  // spcrRepaired2: false,
  // spcrRepaired2Value: '',
  // spcrReplaced2: false,
  // spcrReplaced2Value: '',
  // spcrModified2: false,
  // spcrModified2Value: '',
  // spcrExistingDamage2: false,
  // spcrExistingDamage2Value: '',
  // spclNoevent1: false,
  // spclRepaired2: false,
  // spclRepaired2Value: '',
  // spclReplaced2: false,
  // spclReplaced2Value: '',
  // spclModified2: false,
  // spclModified2Value: '',
  // spclExistingDamage2: false,
  // spclExistingDamage2Value: '',
  // spdrNoevent1: false,
  // spdrRepaired2: false,
  // spdrRepaired2Value: '',
  // spdrReplaced2: false,
  // spdrReplaced2Value: '',
  // spdrModified2: false,
  // spdrModified2Value: '',
  // spdrExistingDamage2: false,
  // spdrExistingDamage2Value: '',
  // spdlNoevent1: false,
  // spdlRepaired2: false,
  // spdlRepaired2Value: '',
  // spdlReplaced2: false,
  // spdlReplaced2Value: '',
  // spdlModified2: false,
  // spdlModified2Value: '',
  // spdlExistingDamage2: false,
  // spdlExistingDamage2Value: '',

  // // front typical
  // spNoevent1: false,
  // spRepaired2: false,
  // spRepaired2Value: '',
  // spReplaced2: false,
  // spReplaced2Value: '',
  // spModified2: false,
  // spModified2Value: '',
  // spExistingDamage2: false,
  // spExistingDamage2Value: '',
  // mcmNoevent1: false,
  // mcmRepaired2: false,
  // mcmRepaired2Value: '',
  // mcmReplaced2: false,
  // mcmReplaced2Value: '',
  // mcmModified2: false,
  // mcmModified2Value: '',
  // mcmExistingDamage2: false,
  // mcmExistingDamage2Value: '',
  // tbNoevent1: false,
  // tbRepaired2: false,
  // tbRepaired2Value: '',
  // tbReplaced2: false,
  // tbReplaced2Value: '',
  // tbModified2: false,
  // tbModified2Value: '',
  // tbExistingDamage2: false,
  // tbExistingDamage2Value: '',
  // tsmNoevent1: false,
  // tsmRepaired2: false,
  // tsmRepaired2Value: '',
  // tsmReplaced2: false,
  // tsmReplaced2Value: '',
  // tsmModified2: false,
  // tsmModified2Value: '',
  // tsmExistingDamage2: false,
  // tsmExistingDamage2Value: '',

  // // roof non-structural
  dNoevent1: false,
  dqty: '',
  dHailDamage2: false,
  dHailDamage2Value: false,
  pdrNoevent1: false,
  pdrExists2: false,
  pdrExists2Value: false,

  // // roof structural
  rbNoevent1: false,
  rbRepaired2: false,
  rbRepaired2Value: '',
  rbReplaced2: false,
  rbReplaced2Value: '',
  rbModified2: false,
  rbModified2Value: '',
  rbExistingDamage2: false,
  rbExistingDamage2Value: '',

  // // side non-structural
  // roparNoevent1: false,
  // roparRepaired2: false,
  // roparRepaired2Value: '',
  // roparReplaced2: false,
  // roparReplaced2Value: '',
  // roparModified2: false,
  // roparModified2Value: '',
  // roparExistingDamage2: false,
  // roparExistingDamage2Value: '',
  // ropalNoevent1: false,
  // ropalRepaired2: false,
  // ropalRepaired2Value: '',
  // ropalReplaced2: false,
  // ropalReplaced2Value: '',
  // ropalModified2: false,
  // ropalModified2Value: '',
  // ropalExistingDamage2: false,
  // ropalExistingDamage2Value: '',
  // riparNoevent1: false,
  // riparRepaired2: false,
  // riparRepaired2Value: '',
  // riparReplaced2: false,
  // riparReplaced2Value: '',
  // riparModified2: false,
  // riparModified2Value: '',
  // riparExistingDamage2: false,
  // riparExistingDamage2Value: '',
  // riparTear2: false,
  // riparTear2Value: '',
  // ripalNoevent1: false,
  // ripalRepaired2: false,
  // ripalRepaired2Value: '',
  // ripalReplaced2: false,
  // ripalReplaced2Value: '',
  // ripalModified2: false,
  // ripalModified2Value: '',
  // ripalExistingDamage2: false,
  // ripalExistingDamage2Value: '',
  // ripalTear2: false,
  // ripalTear2Value: '',
  // qNoevent1: false,
  // qRepaired2: false,
  // qRepaired2Value: '',
  // qReplaced2: false,
  // qReplaced2Value: '',
  // qModified2: false,
  // qModified2Value: '',
  // qExistingDamage2: false,
  // qExistingDamage2Value: '',
  // cNoevent1: false,
  // cRepaired2: false,
  // cRepaired2Value: '',
  // cReplaced2: false,
  // cReplaced2Value: '',
  // cModified2: false,
  // cModified2Value: '',
  // cExistingDamage2: false,
  // cExistingDamage2Value: '',
  // spnNoevent1: false,
  // spnRepaired2: false,
  // spnRepaired2Value: '',
  // spnReplaced2: false,
  // spnReplaced2Value: '',
  // spnModified2: false,
  // spnModified2Value: '',
  // spnExistingDamage2: false,
  // spnExistingDamage2Value: '',
  // ualNoevent1: false,
  // ualRepaired2: false,
  // ualRepaired2Value: '',
  // ualReplaced2: false,
  // ualReplaced2Value: '',
  // ualModified2: false,
  // ualModified2Value: '',
  // ualExistingDamage2: false,
  // ualExistingDamage2Value: '',
  // uarNoevent1: false,
  // uarRepaired2: false,
  // uarRepaired2Value: '',
  // uarReplaced2: false,
  // uarReplaced2Value: '',
  // uarModified2: false,
  // uarModified2Value: '',
  // uarExistingDamage2: false,
  // uarExistingDamage2Value: '',

  // // rear non-structural
  // rdrNoevent1: false,
  // rdrRepaired2: false,
  // rdrRepaired2Value: '',
  // rdrReplaced2: false,
  // rdrReplaced2Value: '',
  // rdrModified2: false,
  // rdrModified2Value: '',
  // rdrExistingDamage2: false,
  // rdrExistingDamage2Value: '',
  // rdlNoevent1: false,
  // rdlRepaired2: false,
  // rdlRepaired2Value: '',
  // rdlReplaced2: false,
  // rdlReplaced2Value: '',
  // rdlModified2: false,
  // rdlModified2Value: '',
  // rdlExistingDamage2: false,
  // rdlExistingDamage2Value: '',

  // // rear structural
  // rrNoevent1: false,
  // rrRepaired2: false,
  // rrRepaired2Value: '',
  // rrReplaced2: false,
  // rrReplaced2Value: '',
  // rrModified2: false,
  // rrModified2Value: '',
  // rrExistingDamage2: false,
  // rrExistingDamage2Value: '',
  // rlNoevent1: false,
  // rlRepaired2: false,
  // rlRepaired2Value: '',
  // rlReplaced2: false,
  // rlReplaced2Value: '',
  // rlModified2: false,
  // rlModified2Value: '',
  // rlExistingDamage2: false,
  // rlExistingDamage2Value: '',
  // qprNoevent1: false,
  // qprRepaired2: false,
  // qprRepaired2Value: '',
  // qprReplaced2: false,
  // qprReplaced2Value: '',
  // qprModified2: false,
  // qprModified2Value: '',
  // qprExistingDamage2: false,
  // qprExistingDamage2Value: '',
  // qplNoevent1: false,
  // qplRepaired2: false,
  // qplRepaired2Value: '',
  // qplReplaced2: false,
  // qplReplaced2Value: '',
  // qplModified2: false,
  // qplModified2Value: '',
  // qplExistingDamage2: false,
  // qplExistingDamage2Value: '',
  // iqprNoevent1: false,
  // iqprRepaired2: false,
  // iqprRepaired2Value: '',
  // iqprReplaced2: false,
  // iqprReplaced2Value: '',
  // iqprModified2: false,
  // iqprModified2Value: '',
  // iqprExistingDamage2: false,
  // iqprExistingDamage2Value: '',
  // iqplNoevent1: false,
  // iqplRepaired2: false,
  // iqplRepaired2Value: '',
  // iqplReplaced2: false,
  // iqplReplaced2Value: '',
  // iqplModified2: false,
  // iqplModified2Value: '',
  // iqplExistingDamage2: false,
  // iqplExistingDamage2Value: '',
  // bprNoevent1: false,
  // bprRepaired2: false,
  // bprRepaired2Value: '',
  // bprReplaced2: false,
  // bprReplaced2Value: '',
  // bprModified2: false,
  // bprModified2Value: '',
  // bprExistingDamage2: false,
  // bprExistingDamage2Value: '',
  // bplNoevent1: false,
  // bplRepaired2: false,
  // bplRepaired2Value: '',
  // bplReplaced2: false,
  // bplReplaced2Value: '',
  // bplModified2: false,
  // bplModified2Value: '',
  // bplExistingDamage2: false,
  // bplExistingDamage2Value: '',
  // fpNoevent1: false,
  // fpRepaired2: false,
  // fpRepaired2Value: '',
  // fpReplaced2: false,
  // fpReplaced2Value: '',
  // fpModified2: false,
  // fpModified2Value: '',
  // fpExistingDamage2: false,
  // fpExistingDamage2Value: '',
  // uvNoevent1: false,
  // uvRepaired2: false,
  // uvRepaired2Value: '',
  // uvReplaced2: false,
  // uvReplaced2Value: '',
  // uvModified2: false,
  // uvModified2Value: '',
  // uvExistingDamage2: false,
  // uvExistingDamage2Value: '',

  // // frame structural
  // fNoevent1: false,
  // fRepaired2: false,
  // fRepaired2Value: '',
  // fReplaced2: false,
  // fReplaced2Value: '',
  // fModified2: false,
  // fModified2Value: '',
  // fExistingDamage2: false,
  // fExistingDamage2Value: '',
  // fsrrNoevent1: false,
  // fsrrRepaired2: false,
  // fsrrRepaired2Value: '',
  // fsrrReplaced2: false,
  // fsrrReplaced2Value: '',
  // fsrrModified2: false,
  // fsrrModified2Value: '',
  // fsrrExistingDamage2: false,
  // fsrrExistingDamage2Value: '',
  // fsrlNoevent1: false,
  // fsrlRepaired2: false,
  // fsrlRepaired2Value: '',
  // fsrlReplaced2: false,
  // fsrlReplaced2Value: '',
  // fsrlModified2: false,
  // fsrlModified2Value: '',
  // fsrlExistingDamage2: false,
  // fsrlExistingDamage2Value: '',
  // rscmNoevent1: false,
  // rscmRepaired2: false,
  // rscmRepaired2Value: '',
  // rscmReplaced2: false,
  // rscmReplaced2Value: '',
  // rscmModified2: false,
  // rscmModified2Value: '',
  // rscmExistingDamage2: false,
  // rscmExistingDamage2Value: '',
  // rspNoevent1: false,
  // rspRepaired2: false,
  // rspRepaired2Value: '',
  // rspReplaced2: false,
  // rspReplaced2Value: '',
  // rspModified2: false,
  // rspModified2Value: '',
  // rspExistingDamage2: false,
  // rspExistingDamage2Value: '',
  // rfrNoevent1: false,
  // rfrRepaired2: false,
  // rfrRepaired2Value: '',
  // rfrReplaced2: false,
  // rfrReplaced2Value: '',
  // rfrModified2: false,
  // rfrModified2Value: '',
  // rfrExistingDamage2: false,
  // rfrExistingDamage2Value: '',
  // rcmNoevent1: false,
  // rcmRepaired2: false,
  // rcmRepaired2Value: '',
  // rcmReplaced2: false,
  // rcmReplaced2Value: '',
  // rcmModified2: false,
  // rcmModified2Value: '',
  // rcmExistingDamage2: false,
  // rcmExistingDamage2Value: '',
};

export { defaultValues };
